os: linux
dist: bionic

language: node_js
node_js:
  - "10.15.3"

stages:
  - "Checkstyle"
  - "Compile and run"
  - "Kong setup"
  - "Tests"
  #- Benchmark
  #  if: branch = master

services:
  - postgresql

before_install:
  - sudo apt-get update
  - mkdir reports/

install:
  - sudo apt-get install -y curl lsb-core
  - npm install -g newman
  - npm install -g jshint
  - echo "deb https://kong.bintray.com/kong-deb `lsb_release -sc` main" | tee -a /etc/apt/sources.list
  - curl -o bintray.key https://bintray.com/user/downloadSubjectPublicKey?username=bintray
  - sudo apt-key add bintray.key
  - sudo apt-get update
  - sudo apt-get install -y kong
  - wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https
  - sudo apt-get update
  - sudo apt-get install -y dotnet-sdk-2.2
  - sudo dotnet tool install kongverge --global
  - cd $HOME/.dotnet/tools
  - ./kongverge --help


before_script:
  - psql -c 'CREATE USER kong;' -U postgres
  - psql -c 'CREATE DATABASE kong OWNER kong;' -U postgres
  - sudo kong migrations bootstrap
  - sudo kong start

jobs:
  include:
    - stage: "Checkstyle"
      name: "Check code style"
      script:
        - jshint src/ --exclude "src/Map.js" > reports/jshint.txt
    - stage: "Compile and run"
      name: "Compile sources and run them"
      script:
        - node src/supermarket_locations.js &
        - node src/atm_locations.js &
        - node src/gas_locations.js &
        - node src/hospital_locations.js &
        - node src/pharmacies_locations.js &
        - node src/wc_locations.js &
        - node src/water_locations.js &
    - stage: "Kong setup"
      name: "Kong setup"
      script:
        - curl -o kong.sh https://gist.githubusercontent.com/losete/29663bd6966fd693df7540fc619f9c15/raw/f5e08b325186cb9c7afce01a627cc80d5c269b81/kong.sh
        - chmod +x kong.sh
        - ./kong.sh
    - stage: "Tests"
      name: "API tests with newman"
      script:
        - newman run tests/newman/gasolineras.postman_collection.json
