os: linux
dist: bionic

language: node_js
node_js:
  - "10.15.3"

services:
  - postgresql

before_install:
  - sudo apt-get update
  - mkdir reports/

install:
  - sudo apt-get install -y curl lsb-core
  - npm install -g newman
  - npm install -g jshint
  # Install Kong
  - echo "deb https://kong.bintray.com/kong-deb `lsb_release -sc` main" | tee -a /etc/apt/sources.list
  - curl -o bintray.key https://bintray.com/user/downloadSubjectPublicKey?username=bintray
  - sudo apt-key add bintray.key
  - sudo apt-get update
  - sudo apt-get install -y kong
  # Install kongverge
  - wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https
  - sudo apt-get update
  - sudo apt-get install -y dotnet-sdk-2.2
  - sudo dotnet tool install kongverge --global
  # Install siege
  - wget http://download.joedog.org/siege/siege-3.1.4.tar.gz
  - tar -zxvf siege-3.1.4.tar.gz
  - cd siege-*/
  - sudo apt-get install build-essential
  - ./configure
  - make
  - sudo make install
  - cd ..

before_script:
  # Configure enviroment and launch Kong
  - psql -c 'CREATE USER kong;' -U postgres
  - psql -c 'CREATE DATABASE kong OWNER kong;' -U postgres
  - sudo kong migrations bootstrap
  - kong version
  - sudo kong start
  # Check code style
  - jshint src/ --exclude "src/Map.js"
  # Compile sources and run them
  - npm install src
  - node src/atm_locations.js &
  - node src/gas_locations.js &
  - node src/supermarket_locations.js &
  - node src/hospital_locations.js &
  - node src/pharmacies_locations.js &
  - node src/wc_locations.js &
  - node src/water_locations.js &

script:
  - curl -o kong.sh https://gist.githubusercontent.com/losete/29663bd6966fd693df7540fc619f9c15/raw/2561cbe995b39af5e745366faaeaa623ed77ee27/kong.sh
  - chmod +x kong.sh
  - ./kong.sh


after_success:
  # Unit API tests with newman
  - newman run tests/newman/gasolineras.postman_collection.json
  - newman run tests/newman/cajeros.postman_collection.json
  - newman run tests/newman/banos.postman_collection.json
  - newman run tests/newman/farmacias.postman_collection.json
  - newman run tests/newman/hospitales.postman_collection.json
  - newman run tests/newman/puntosAgua.postman_collection.json
  - newman run tests/newman/supermercados.postman_collection.json
  # Plugin tests
  - newman run tests/newman/metrics.postman_collection.json
  - newman run tests/newman/bodyTests.postman_collection.json
  - newman run tests/newman/cachePlugin.postman_collection.json
  - newman run tests/newman/caching.postman_collection.json
  - curl -X POST http://localhost:8001/consumers/corunapi/key-auth -d '13rue13a12345'
  - curl -X POST http://localhost:8001/plugins --data "name=key-auth"
  - newman run tests/newman/apikey.postman_collection.json
  #  Creating the configuration file
  - cd $HOME/.dotnet/tools
  - sudo ./kongverge --host:localhost export kongfiles

before_deploy:
  # Benchmarking
  - siege -t 60S -c 250 -iqf tests/benchmarks/urls.txt
  - siege -t 60S -c 250 -q http://127.0.0.1:3013/
  - siege -t 60S -c 200 -iqf tests/benchmarks/urls.txt
  - siege -t 60S -c 200 -q http://127.0.0.1:3013/
  - siege -t 60S -c 150 -iqf tests/benchmarks/urls.txt
  - siege -t 60S -c 150 -q http://127.0.0.1:3013/
  - siege -t 60S -c 100 -iqf tests/benchmarks/urls.txt
  - siege -t 60S -c 100 -q http://127.0.0.1:3013/
  - siege -t 60S -c 75 -iqf tests/benchmarks/urls.txt
  - siege -t 60S -c 75 -q http://127.0.0.1:3013/
  - siege -t 60S -c 50 -iqf tests/benchmarks/urls.txt
  - siege -t 60S -c 50 -q http://127.0.0.1:3013/
  - siege -t 60S -c 25 -iqf tests/benchmarks/urls.txt
  - siege -t 60S -c 25 -q http://127.0.0.1:3013/
  - siege -t 60S -c 10 -iqf tests/benchmarks/urls.txt
  - siege -t 60S -c 10 -q http://127.0.0.1:3013/
  - siege -t 60S -c 10 -q "http://www.mapabase.es/arcgis/rest/services/Otros/Gasolineras/FeatureServer/0/query?where=localidad+%3D+%27CORUÑA+%28A%29%27&outFields=latitud,longitud,horario,dirección,rótulo&f=json"

deploy:
  provider: releases
  api_key: $GHToken
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
      - losetazo@gmail.com
    on_success: always
    on_failure: always
